base-model: cointegrated/rubert-tiny2

max-tokens: 200

train:
  epoches: 50
  lr: 0.00001
  batch-size: 64
  num-workers: 5
  freeze: false
  dropout_rate: 0.1
  use_prev_label: true
  weights: [1, 2, 2, 3, 2.5, 3, 2.5]
