model_name: cointegrated/rubert-tiny2
num_labels: 7
id2label:
  0: O
  1: B-SPELL
  2: I-SPELL
  3: B-MONSTER
  4: I-MONSTER
  5: B-ITEM
  6: I-ITEM
label2id:
  O: 0
  B-SPELL: 1
  I-SPELL: 2
  B-MONSTER: 3
  I-MONSTER: 4
  B-ITEM: 5
  I-ITEM: 6
learning_rate: 1e-05
freeze: false
hidden_size: 256
dropout_rate: 0.1
use_prev_label: true
