model_name: cointegrated/rubert-tiny2
num_labels: 3
id2label:
  0: O
  1: B-OBJECT
  2: I-OBJECT
label2id:
  O: 0
  B-OBJECT: 1
  I-OBJECT: 2
learning_rate: 1e-05
freeze: false
hidden_size: 256
dropout_rate: 0.1
use_prev_label: false
weights:
- 0.3333333432674408
- 0.3333333432674408
- 0.3333333432674408
